name: build-and-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build Tetris --configuration Release

      - name: Run Tests
        run: dotnet test
